
package tp2_soap_client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelWebService", targetNamespace = "http://tp2_soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelWebService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<tp2_soap_client.Offre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterDisponibilites", targetNamespace = "http://tp2_soap/", className = "tp2_soap_client.ConsulterDisponibilites")
    @ResponseWrapper(localName = "consulterDisponibilitesResponse", targetNamespace = "http://tp2_soap/", className = "tp2_soap_client.ConsulterDisponibilitesResponse")
    @Action(input = "http://tp2_soap/HotelWebService/consulterDisponibilitesRequest", output = "http://tp2_soap/HotelWebService/consulterDisponibilitesResponse")
    public List<Offre> consulterDisponibilites(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "efectuerReservation", targetNamespace = "http://tp2_soap/", className = "tp2_soap_client.EfectuerReservation")
    @ResponseWrapper(localName = "efectuerReservationResponse", targetNamespace = "http://tp2_soap/", className = "tp2_soap_client.EfectuerReservationResponse")
    @Action(input = "http://tp2_soap/HotelWebService/efectuerReservationRequest", output = "http://tp2_soap/HotelWebService/efectuerReservationResponse")
    public String efectuerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

}
